# Generated by Django 4.1 on 2023-11-28 22:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_pictures')),
                ('company_contact_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobhub.companycontactinfo')),
                ('company_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobhub.companyinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('resume', models.FileField(blank=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='JobHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='JobSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(blank=True, max_length=255)),
                ('post_time', models.DateField()),
                ('due_time', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('estimate_pay_lower', models.PositiveIntegerField()),
                ('estimate_pay_upper', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OtherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(blank=True)),
                ('interests', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField(blank=True, null=True)),
                ('type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_pictures')),
                ('contact_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobhub.contactinfo')),
                ('education', models.ManyToManyField(to='jobhub.education')),
                ('other_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobhub.otherinfo')),
                ('personal_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobhub.personalinfo')),
                ('project_experience', models.ManyToManyField(to='jobhub.projectexperience')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_experience', models.ManyToManyField(to='jobhub.workexperience')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobhub.companyprofile')),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobhub.jobdetail')),
                ('highlight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobhub.jobhighlight')),
                ('summary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobhub.jobsummary')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('overall_rating', models.IntegerField()),
                ('interview_progression_rating', models.IntegerField()),
                ('application_response_time_rating', models.IntegerField()),
                ('benefits_during_interview_rating', models.IntegerField()),
                ('interview_atmosphere_rating', models.IntegerField()),
                ('interview_etiquette_rating', models.IntegerField()),
                ('review', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('overall_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('interview_progression_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('application_response_time_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('benefits_during_interview_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('interview_atmosphere_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('interview_etiquette_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('five_star_rating', models.IntegerField()),
                ('four_star_rating', models.IntegerField()),
                ('three_star_rating', models.IntegerField()),
                ('two_star_rating', models.IntegerField()),
                ('one_star_rating', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobhub.companyinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobhub.companyreview'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='individual_reviews',
            field=models.ManyToManyField(to='jobhub.individualreview'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='public_staff_list',
            field=models.ManyToManyField(to='jobhub.userprofile'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycontactinfo',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobhub.companyinfo'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitdate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('all', 'All'), ('reviewed', 'Reviewed'), ('interviewed', 'Interviewed'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='all', max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobhub.companyprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobhub.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
